---
apiVersion: v1
data:
  sender-config.yml: |-
    # Resolver name to zabbix host mapping
    #   left side (key) is Alertmanager's resolver name
    #   right side (value) is Zabbix host name.
    zabbix-alertmanager: openshift
  prov-config.yml: |-
    # Name of the host in zabbix
    - name: openshift
      hostGroups:
        - prometheus
      # tag and deploymentStatus are inventory fields currently supported for an host
      tag: prometheus
      deploymentStatus: 0
      # itemDefault* below, defines item values when not specified in a rule
      itemDefaultApplication: prometheus
      # For history and trends in zabbix 2.x you have to put those in days like 7 or 90
      itemDefaultHistory: 5d
      itemDefaultTrends: 5d
      itemDefaultTrapperHosts: # Hosts permitted to send data (your webhook external CIDR, default is from everywhere)
      # Path to the alerts containing folder
      alertsDir: /tmp/alerts
kind: ConfigMap
metadata:
  name: zal

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-monitoring
spec:
  podSelector:
    matchLabels:
      name: zal
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
  policyTypes:
  - Ingress

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: zabbix
    k8s-app: zal
  name: zal
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: zal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: zal
        name: zal
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - zal
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - send
        - --log.level=debug
        - --zabbix-addr=zabbix-server:10051
        - --default-host=infra
        - --hosts-path=/etc/zal/sender-config.yml
        #image: quay.io/devopyio/zabbix-alertmanager:v1.2.4
        image: docker.io/jontow/zabbix-alertmanager:latest
        imagePullPolicy: Always
        name: zal
        ports:
        - containerPort: 9095
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/zal
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: zal
        name: config-volume
